version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=locat_lost
    command: >
      sh -c "php artisan migrate:fresh --seed &&
             php artisan db:seed --class=AdminSeeder &&
             php artisan db:seed --class=StationNamesLocations &&
             apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locat_lost
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/locat_lost.sql:/docker-entrypoint-initdb.d/locat_lost.sql

  npm:
    image: node:18
    container_name: laravel_npm
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["npm", "run", "dev"]

volumes:
  mysql_data:
